package SNePSLOG;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 16 17:04:55 EET 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int WITHSOME = 13;
	public static final int UNTRACE = 65;
	public static final int NORMAL = 53;
	public static final int TRACE = 62;
	public static final int ARROW = 19;
	public static final int LCURLY = 15;
	public static final int ASKWH = 37;
	public static final int ASK = 35;
	public static final int REMOVEFROMCONTEXT = 55;
	public static final int DEFINEFRAME = 41;
	public static final int SETDEFAULTCONTEXT = 57;
	public static final int DEFINEPATH = 42;
	public static final int WITHALL = 14;
	public static final int UNLABELED = 64;
	public static final int ALL = 27;
	public static final int DOUBLEIMPLICATION = 22;
	public static final int LP = 4;
	public static final int RP = 7;
	public static final int ORENTAIL = 18;
	public static final int NOT = 23;
	public static final int UNDEFINEPATH = 63;
	public static final int PARSING = 28;
	public static final int KPLUS = 71;
	public static final int EM = 6;
	public static final int ANDOR = 24;
	public static final int SETCONTEXT = 56;
	public static final int KSTAR = 70;
	public static final int EXPERT = 46;
	public static final int COMA = 11;
	public static final int SETMODE3 = 60;
	public static final int SETMODE2 = 59;
	public static final int QM = 3;
	public static final int SETMODE1 = 58;
	public static final int ACTING = 30;
	public static final int NEXISTS = 25;
	public static final int DOMAINRESTRICT = 73;
	public static final int LISTTERMS = 50;
	public static final int CONVERSE = 68;
	public static final int WF = 12;
	public static final int DT = 9;
	public static final int CLEARKB = 40;
	public static final int ASKIFNOT = 36;
	public static final int INFERENCE = 31;
	public static final int LOAD = 52;
	public static final int PERFORM = 54;
	public static final int SHOW = 61;
	public static final int THRESH = 26;
	public static final int ADDTOCONTEXT = 34;
	public static final int EOF = 0;
	public static final int COMPOSE = 69;
	public static final int DEMO = 43;
	public static final int CL = 8;
	public static final int ACTIVATEASSERT = 33;
	public static final int LISTASSERTEDWFFS = 48;
	public static final int LISTCONTEXTS = 49;
	public static final int ANDENTAIL = 17;
	public static final int ADJUST = 66;
	public static final int OR = 21;
	public static final int error = 1;
	public static final int II = 10;
	public static final int ID = 5;
	public static final int LISP = 47;
	public static final int DESCRIBETERMS = 45;
	public static final int TRANSLATION = 29;
	public static final int DASH = 67;
	public static final int LISTWFFS = 51;
	public static final int DESCRIBECONTEXT = 44;
	public static final int NM = 2;
	public static final int AND = 20;
	public static final int CLEARINFER = 39;
	public static final int ACTIVATE = 32;
	public static final int IRR = 72;
	public static final int ASKWHNOT = 38;
	public static final int RCURLY = 16;
}
