package SnepsLog;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 24 18:26:44 EET 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NE = 19;
  public static final int LT = 11;
  public static final int LP = 9;
  public static final int CL = 13;
  public static final int RP = 10;
  public static final int OO = 6;
  public static final int II = 18;
  public static final int DT = 17;
  public static final int ID = 4;
  public static final int OE = 21;
  public static final int MT = 12;
  public static final int AO = 3;
  public static final int WFF = 23;
  public static final int COMA = 22;
  public static final int EOF = 0;
  public static final int ML = 15;
  public static final int SM = 2;
  public static final int AE = 20;
  public static final int error = 1;
  public static final int AA = 7;
  public static final int EQ = 14;
  public static final int EM = 16;
  public static final int NM = 5;
  public static final int QM = 8;
}

